target:
  service: sing
  name: msrresrchvc

environment:
  image: amlt-sing/ptca-1.13.1-cuda11.7
  setup:
    - pip install --user -U -r requirements.txt
    # - bash scripts/download_dataset.sh

code:
  # local directory of the code. this will be uploaded to the server.
  local_dir: $CONFIG_DIR

# data:
#   # local_dir: /mnt/r2pdev/experiments/IS0Pert-yan/dataset_full
#   remote_dir: projects/yan-ISPert/dataset
#   ### remote_dir only can read storage_account_name/container_name/amulet/


storage:
  my_output:
    storage_account_name: r2pdev
    container_name: experiments
    mount_dir: /blob/r2pdev/experiments
  

jobs:
- name: train
  sku: G8-V100
  process_count_per_node: 8
  command:
    - bash scripts/launch_train.sh
  priority: high  # high, medium, low
  execution_mode: basic  # managed, basic
  sla_tier: premium  # basic, standard, premium
  submit_args:
    max_run_duration_seconds: 1209600
    # env:
    #   AZUREML_COMPUTE_USE_COMMON_RUNTIME: false
