logging:
    type: syslog
libfuse:
    attribute-expiration-sec: 240
    entry-expiration-sec: 240
    negative-entry-expiration-sec: 120
file_cache:
    path: /mnt/blobfusetmp/fusong4dataset/dataset
azstorage:
    endpoint: https://fusong4dataset.blob.core.windows.net
    container: dataset
    update-md5: false
    validate-md5: false
    virtual-directory: true
components:
    - libfuse
    - file_cache
    - attr_cache
    - azstorage
